--inserting id for initialisation  of execution


DEFINE logpath=&&1;
DEFINE logfilename=&&2;
SPOOL &&logpath/&&logfilename

SET echo on;
SET SERVEROUTPUT ON ;
SET timing on;

prompt "inserting id for initialisation  of execution"

CREATE SEQUENCE SEQ_EXECUTIONCONTROLER MINVALUE 20000 START WITH 20000 INCREMENT BY 1 CACHE 20;
DROP TABLE AR_EXECUTION_CONTROLER CASCADE CONSTRAINTS;
CREATE TABLE AR_EXECUTION_CONTROLER 
(
    EXECUTION_ID NUMBER,
    EXECUTION_TIMESTAMP TIMESTAMP
);
INSERT INTO AR_EXECUTION_CONTROLER SELECT SEQ_EXECUTIONCONTROLER.NEXTVAL ,SYSTIMESTAMP FROM DUAL;
COMMIT;
set time off
/
EXIT